In [24]:
!pip install keras
!pip install loadtxt

ERROR: Could not find a version that satisfies the requirement loadtxt (from versions: none)
ERROR: No matching distribution found for loadtxt


In [25]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import numpy as np


In [26]:
dataset = loadtxt('/content/pima-indians-diabetes.csv',delimiter=',')

In [27]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [28]:
x = dataset[:,0:8]
y = dataset[:,8]

In [29]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [30]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [31]:
model = Sequential()
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [32]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 3ms/step - loss: 2.6748 - accuracy: 0.4792
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1865 - accuracy: 0.5990
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8904 - accuracy: 0.6263
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7585 - accuracy: 0.6328
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7163 - accuracy: 0.6510
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7422 - accuracy: 0.6354
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7334 - accuracy: 0.6589
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6687 - accuracy: 0.6576
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6835 - accuracy: 0.6497
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6662 - accuracy: 0.6549
Epoch 11/

In [33]:
_,accuracy=model.evaluate(x,y)

24/24 [==============================] - 0s 2ms/step - loss: 0.4987 - accuracy: 0.7539


In [34]:
print("Accuracy of model is",(accuracy*100))

Accuracy of model is 75.390625


In [40]:
prediction =model.predict(x)

24/24 [==============================] - 0s 2ms/step


In [41]:
exec("for i in range(5):print(x[i].tolist(),prediction[i],y[i])")

[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] [0.7364628] 1.0
[1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] [0.11386129] 0.0
[8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] [0.7543636] 1.0
[1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] [0.19461973] 0.0
[0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] [0.84989774] 1.0
